
build_prod:
  stage: build
  image: node:lts-alpine3.11
  script:
    - "npm install"
    - CI=false npm run build
  artifacts:    
      paths:      
         # Build folder      
         - build/    
      expire_in: 1 hour
  only:
    - morteza

deploy_prod:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - build_prod
  script:
    - echo "copying files to s3://flatlaystorefronts/"
    - aws s3 cp ./dbuild s3://flatlaystorefront/ --recursive
    - aws cloudfront create-invalidation --distribution-id=E2M36M6JJ7FMID --paths /
    - echo "Copying files complete"
  only:
    - morteza



stages:
  - build
  - deploy
