import { Box, Flex, VStack } from '@chakra-ui/react'
import AppCard from 'common/card/AppCard'
import FieldLabel from 'common/form/fieldLabel/FieldLabel'
import AppInput from 'common/form/textbox/AppInput'
import AppTypography from 'common/typography/AppTypography'
import { addressBookService } from 'lib/apis/address/addressServices'
import React, { useCallback, useEffect, useState } from 'react'
import { useMutation } from 'react-query'
import ShopInfoAddress from './parts/address/shopInfoAddress'
import ShopInfoSubmit from './parts/submit/ShopInfoSubmit'
import { useProfile } from "hooks/useProfile/useProfile"

export interface IstatesShopInfo {
  description: string,
  addressBookID: string
}

function RegisterShopInfo() {
  const { shop } = useProfile()
  const addressService = useMutation(() => addressBookService())
  const [States, setStates] = useState<IstatesShopInfo>({
    description: null,
    addressBookID: null
  })
  const address = addressService.data?.data?.data

  const updateStates = useCallback((key: string, value: string) => setStates((prev: IstatesShopInfo) => ({ ...prev, [key]: value })), [])

  // Fetch address user
  useEffect(() => addressService.mutate(), [])

  // Get addressBookID
  useEffect(() => updateStates("addressBookID", address && address.length ? address[0]._id : null), [addressService.data])

  // Update store name as shop
  useEffect(() => shop.description && updateStates("description", shop.description), [shop])

  return (
    <VStack width={"100%"} spacing={4} justifyContent="center" align={"stretch"}>
      <AppCard>
        <VStack align={"stretch"} color="#FFF" spacing={7}>

          <VStack align={"stretch"}>
            <Box><AppTypography size='18px' weight='bolder'>Store info</AppTypography></Box>
            <Box><AppTypography size='14px' color={"#C2C2C2"}>Name your store and provide the shipping address(es) for your orders</AppTypography></Box>
          </VStack>

          <Box><AppInput name='name' label='Store Name' value={States.description} onChange={(e: any) => updateStates("description", e.target.value)} placeholder='Enter max 20 characters.' isRequired /></Box>

          <VStack align={"stretch"}>
            <Box><AppInput name='url' label='Store URL' value={'https://droplinked.com/' + shop.name} isReadOnly /></Box>
            <Box>
              <AppTypography size='14px' color={"rgb(128, 128, 128)"}>The URL generated by droplinked refers to your store's web address.</AppTypography>
            </Box>
          </VStack>

          <VStack align={"stretch"}>
            <Box><FieldLabel isRequired label='Shop Address' /></Box>
            <Box>
              <AppTypography size='14px' color={"#C2C2C2"}>The location of you / your physical store / where you store your products.</AppTypography>
            </Box>
          </VStack>
          <Box><ShopInfoAddress addressService={addressService} /></Box>
        </VStack>
      </AppCard>
      <Flex justifyContent={"right"}><ShopInfoSubmit States={States} /></Flex>
    </VStack>
  )
}

export default RegisterShopInfo