import "./Terms.scss"
import {
	BrowserRouter as Router,
	Switch,
	Route,
	Link,
	useParams,
} from 'react-router-dom';


function Terms() {

    return (
        <div className="terms-wrap">
            <div className="terms-body">
                <div className="terms-title"><p>Flatlay.io and FLATLAY® Mobile App Terms of Service</p> </div>
                <div className="terms-text">
                    <p> The Flatlay mobile app (“FLATLAY”) is available for Android OS and Apple iOS devices and offers you to discover and share collections of products. FLATLAY Inc., a Delaware company, is the genius behind and owner of Flatlay. The terms of this agreement (“Agreement”) make up a binding legal agreement between you, as an individual or entity, and “FLATLAY, Inc.” By accessing the Flatlay website at www.flat-lay.com (“Site”) and/or downloading FLATLAY you agree to be bound by both this Agreement, our privacy policy (“Privacy Policy,” available for download at www.flat-lay.com/privacy) and our Flatlay Card Terms of Service (“Flatlay Card Terms,” available for download at www.flatlay.io/terms). Please review all three agreements carefully before using the Services, including installing Flatlay and setting up your Flatlay account, as you do agree to be bound by all of the agreements. </p>
                    <p> In this Agreement, the word “Service” or “Services” will refer to all content available on our Site, as well as the mobile version of the Site, and the FLATLAY Apps. Additional services are available within Flatlay and these services are governed by their respective terms, available for download at www.flat-lay.com/terms. Users of Flatlay may also use the Flatlay card program (“Flatlay Card”) and the terms of use for the Flatlay Card are available at www.flat-lay.com/terms. The content available on the app in Flatlay may differ from the content available on the Site and vice versa. </p>
                    <p> Visitors to our Site (“Visitors”), individuals who have downloaded and installed Flatlay and setup an account with Flatlay (“Flatlay Members”) and Flatlay Members who have signed up for a Flatlay Card (“Flatlay Card Members”) are all covered by this Agreement. You will be asked to accept this Agreement when you become a Flatlay Card Member. You should save a copy of this Agreement for your records. </p>
                    <p> We of course welcome any comments or suggestions from any of these users on all of our Services at support (at) flatlay.io. </p>
                    <p> To the extent you have access to or are using Flatlay or the Site without having completed an agreement with FLATLAY, Inc., you are hereby notified that your continued use of the Services is nonetheless subject to many of the terms and conditions of this Agreement. </p>
                    <p><span>NOTICE: </span>Please take note that this Agreement contains disclaimers of warranties and liability. </p>
                    <p><span>Binding Effect and Agreement Changes.</span> This is a binding agreement. By using the Site or any services provided in connection with the Site, you agree to abide by this Agreement, as they may be amended by FLATLAY, Inc. from time to time in its sole discretion. FLATLAY, Inc. will post a notice on the Site any time this Agreement has been changed or otherwise updated. It is your responsibility to review this Agreement periodically, and if at any time you find this Agreement unacceptable, you must immediately leave the Site and cease all use of the Site and Flatlay. YOU AGREE THAT BY USING THE SERVICE YOU REPRESENT THAT YOU ARE AT LEAST 13 YEARS OLD AND THAT YOU ARE LEGALLY ABLE TO ENTER INTO THIS AGREEMENT. </p>
                    <p><span>Accessing the Services.</span> Although information about Flatlay is available on the Site, you need to download and install Flatlay and fully setup your profile to get the most out of the Services.Further, you will need to setup your Flatlay Card as described in the Flatlay Card Terms. </p>
                    <p> You may not reverse engineer, decompile, disassemble or otherwise attempt to discern the source code of the components of Flatlay, nor may you reproduce all or any portion of the components of Flatlay or distribute any components without FLATLAY, Inc.’s written permission. The contents of the Site and Flatlay belong to FLATLAY, Inc. and are protected through trademark and copyright laws. All contents of the Site and Flatlay are: Copyright © 2017 FLATLAY, Inc., 6201 Hollywood Boulevard, Suite 3207, Los Angeles, CA 90028. All rights reserved. </p>
                    <p> From time to time FLATLAY, Inc. may update Flatlay. This may also mean that you are not able to access and/or use Flatlay fully or partly as you once were with an existing device. As of the effective date of this Agreement, the minimum requirements for Flatlay are: an Apple iOS device running iOS 8 or higher that you own or control or an Android OS device running Android OS 2.1 up to OS 2.3 with an account for either device that allows access to the Play Store or Apple App Store in a country that offers Flatlay. Further, Flatlay requires an Internet connection to fully function. As FLATLAY, Inc. does not provide your Internet connection, it makes no warranties that you will, in fact, always have access to the Internet. </p>
                    <p><span>Your Flatlay Card.</span> We reserve the right to refuse a Flatlay Card to anyone for any reason within the confines of the law. You also take full responsibility for keeping your username and password confidential, and you agree to contact us immediately at support (at) flatlay.io if you think your Flatlay Profile has been compromised. </p>
                    <p> You will be asked during account setup and periodically during account maintenance to authorize FLATLAY, Inc. to retrieve information about you that you keep with other third parties (e.g., retailers, e-commerce sites). We will retrieve the information but we do not vet the information (for example, for accuracy, legality or infringement). Because this will require FLATLAY to contact third parties, this may mean that our ability to access information is limited by the third party’s ability to provide access to the information. Our Privacy Policy, available at www.flat-lay.com/privacy, governs our management of this information. </p>
                    <p> Scope of the Service. Flatlay offers you tools that can help you track your spending and find trends. This means that the Services include the delivery of the graphics and/or images, text, audio, video, data compilations, electronic communication, software, databases, and other visuals or audio. This also means that you your personal inputs are necessary to get the most out of Flatlay and we may provide you with information related to third party products, services, tips and/or suggestions. </p>
                    <p><span>FLATLAY DOES NOT PROVIDE ANY INVESTMENT ADVICE, TAX ADVICE OR LEGAL ADVICE.</span> The Site and Flatlay are there for you to educate yourself; the Service is provided as is and is solely for informational purposes, not for advice. FLATLAY, Inc. urges you to consider seeking advice from a financial planner, an attorney or tax advisor regarding your financial matters. None of the information contained on the Site or in the Service constitutes a solicitation, offer, opinion or recommendation by FLATLAY, Inc. or any of its third-party data providers, to buy or sell any securities or other financial instruments or to provide legal, tax, accounting or investment advice or services regarding the viability, suitability or potential profitability of any security or investment. </p>
                    <p> FLATLAY, Inc. makes a reasonable effort to ensure that the Service is up to date and accurate, and you acknowledge and agree that FLATLAY relies on the accuracy of outside sources, which may or may not be completely thorough and accurate. FLATLAY reserves the right to correct any information provided and makes no warranties as to the accuracy or completeness of the information provided. Neither FLATLAY, Inc. nor any outside content providers shall be liable for any errors, inaccuracies or delays in content, or for any actions taken in reliance thereon. AS FURTHER DISCUSSED BELOW, FLATLAY EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESSED OR IMPLIED, AS TO THE ACCURACY OF ANY THE CONTENT PROVIDED, OR AS TO THE FITNESS OF THE INFORMATION FOR ANY PURPOSE. </p>
                    <p> Please report any errors or mistakes you may find to support (at) flatlay.io and be sure to include a detailed description of the issue, the URL(s) where the error occurs, and which internet browser you were using. </p>
                    <p> Please also note that some functionality will depend on your other service providers providing access to certain information. For example, some platforms are not setup to interface directly with third party programs, but may allow you to download the relevant data and that data can then be uploaded here. Further, your financial institution may limit access to certain types of accounts (e.g., credit card, savings account). FLATLAY can help you overcome some of these issues, but others problems may remain until your financial institution takes steps to open its platform for integration. </p>
                    <p> Although promotional credit and coupons may be available to users of Flatlay and/or the Flatlay Card, FLATLAY is not a money transmitter or money transfer service. </p>
                    <p><span>Rights Grant; Restrictions.</span></p>
                    <p> The Site and Service may contain original works created by FLATLAY. These works are FLATLAY Inc.’s exclusive intellectual property and are proprietary. As such, the Site and Service are protected by this Agreement, domestic and foreign contractual and intellectual property law (such as, but not limited to patent, copyright and trademark laws), which is further discussed below. </p>
                    <p> You are granted a non-exclusive, non­-transferable limited right to access the Site and Service for research purposes that can be revoked. Every natural or legal person requires an individual user account, and you may not share your username and password with another person, legal or natural. </p>
                    <p> The Service is protected by copyright, intellectual property laws, and other laws that prevent any and all unauthorized use, access and manipulation. FLATLAY grants to you only the following rights: (a) the right to electronically display the Service through the Site web portal for your use, (b) the right to display the Service to others in the course of ordinary business, (c) the right to use the Service as permitted by applicable copyright law(s), and (d) the right to print portions of the Service on an ad hoc basis for your personal purpose(s). You are prohibited from offering for commercial resale or distribution any of the Service, and you are prohibited from using any of the Service or the Site or any of its intellectual property to compete with FLATLAY. This section is the limit of your rights, and this Agreement does not grant to you any propriety interest in any FLATLAY property. Your use must comply at all times with all applicable laws, rules or regulations. </p>
                    <p> You may not copy, download, store, publish, transmit, retransmit, transfer, distribute, disseminate, circulate, sell, resell or otherwise use the Service or any portion of the Service, in any form or by any means, except (i) as expressly permitted by this Agreement, (ii) with FLATLAY’s prior written permission, or (iii) if not otherwise expressly prohibited by this Agreement or as allowed under the fair use provision of the Copyright Act (17 U.S.C.A. § 107). ICE may also discontinue or change the Service, or its availability to you, at any time. </p>
                    <p> Nothing contained on the Site or in the app should be understood as granting you a license to use any of the trademarks, service marks, or logos owned by FLATLAY or by any third party. </p>
                    <p><span>Use.</span> The Service is to only be used in accordance with this Agreement. FLATLAY retains the right to temporarily or permanently block access to the Services (at its sole discretion) if FLATLAY has reason to believe that the Services may be used for an improper purpose or otherwise in violation of the terms of this Agreement. You must report to FLATLAY any misuse, abuse, or compromise of the Service of which you become aware. </p>
                    <p> Flatlay makes it possible for you to use sites and services outside of Flatlay to distribute referral links to your network. Be mindful of your conduct both inside the Flatlay App and outside as it relates to Flatlay. For example, do not engage in unauthorized commercial communications or multi-level marketing schemes, solicit and/or collect App login information, collect users' content or information using traditional or automated means, or access an account belonging to someone else. If you have any questions about your conduct, please let us know. </p>
                    <p> Further, we may allow users to upload lifestyle content such as images and then tag them with brands or stores as part of creating a user’s shopping collection. These photos and the information that is attached to the photos are the expression of the opinions and information of the user posting the photo. Flatlay neither agrees or approves of the opinions or information, nor does either warrant the exhaustiveness, suitability, or accuracy of the opinion or information. </p>
                    <p> As a result of the user’s experience and feedback or other reasons, we may from time to time make images or logos of various companies available on our website or via the Flatlay App. Use of these photos does not mean that any of the owners or licensees of this contact are providing an endorsement, authorization, sponsorship, or affiliation with FLATLAY. </p>
                    <p><span>Account Security.</span> As mentioned above in this agreement as well as in the Flatlay Card Terms,if you have a reason to believe that your account is no longer secure (for example, in the event of a loss, theft or unauthorized disclosure or use of your ID, password, or any credit, debit, or charge card number stored), notify FLATLAY of the problem to avoid possible liability for any unauthorized charges, access or use of your Flatlay Profile. </p>
                    <p> At FLATLAY, we value and encourage innovation and collaboration. We work to bring the most efficient, elegant solutions to streamline the Flatlay App. This means that we may work with strategic partners for services, including payment processing or customer data management. Your use of the FLATLAY products means you consent to our use of these third parties. We may share your information with these third parties subject to the provisions in our Privacy Policy, as amended. </p>
                    <p><span>Mobile and Email Alerts.</span> Your Android or Apple device may provide FLATLAY the opportunity to send you alerts and/or messages through your device and/or email. You can make changes to these preferences within your Flatlay Profile. If your contact information used in your Flatlay Profile changes, then you are responsible for updating your Flatlay Profile timely. We will never send your password through an alert. </p>
                    <p><span>Privacy Policy.</span> FLATLAY respects your privacy. A complete statement of Flataly’s current privacy policy can be found by visiting www.flat-lay.com/privacy. Flatlay’s privacy policy is expressly incorporated into this Agreement by this reference. Any notice(s) of changes to the Privacy Policy will be posted to the FLATLAY website. </p>
                    <p><span>Regional Concerns.</span> FLATLAY, Inc. is a Delaware company and its clients are residents of the United States. Selected services may be available to those outside of the U.S. Contact us for more information! </p>
                    <p> You are given access to the Site and Flatlay based on your home location. To comply with local laws, you may not use Flatlay outside of your home country for more than thirty (30) days at one time. FLATLAY reserves the right to suspend access should Flatlay suspect that a user has accessed Flatlay for more than the proscribed time period. Your use of or access to the Site and/or Flatlay should not be construed as Flatlay’s purposefully availing itself of the benefits or privilege of doing business in any state or jurisdiction other than Delaware. </p>
                    <p> You acknowledge that you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country, and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. Further, you recognize that the Flatlay Mobile App may ask you for your location when you use it to give you targeted, geographically specific information. You can disable or enable these settings within your device. Contact your device manufacturer for more information. </p>
                    <p> Change to Agreement. As mentioned above, FLATLAY may change the terms of this Agreement at any time by notifying you of the change in writing or electronically (including without limitation, by email or by posting a notice on the Site that the terms have been “updated” or similar language). You agree to be bound by such changes by using Service after changes are made to this Agreement. If you do not consent to any part of the Agreement, please do not access the Service as your access constitutes your acceptance of these terms. </p>
                    <p><span>Downloading Flatlay from Apple Inc. (“Apple”)?</span> If you downloaded Flatlay from Apple, then the following terms of this Agreement also apply: </p>
                    <p><span>Acknowledgement.</span> You acknowledge that this Agreement is concluded between you and FLATLAY and not between you and Apple. </p>
                    <p> Maintenance and Support. Apple has no obligation whatsoever to furnish any maintenance and support services with respect to Flatlay. </p>
                    <p> Warranty. In the event of any failure of Flatlay to conform to any applicable warranty, you may notify Apple, and Apple will refund your purchase price, if any, for Flatlay; to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to Flatlay. </p>
                    <p> Product Claims. FLATLAY, and not Apple, is responsible for addressing any of your claims or any third party relating to Flatlay or your possession and/or use of Flatlay, including, but not limited to: (i) product liability claims; (ii) any claim that the Flatlay fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation. </p>
                    <p> Intellectual Property Rights. In the event of any third party claim that Flatlay or your possession and use of Flatlay infringes that third party’s intellectual property rights, FLATLAY, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim. </p>
                    <p> Developer Name and Address. FLATLAY Inc., 6201 Hollywood Boulevard, Suite 3207, Los Angeles, CA 90028. </p>
                    <p> Third Party Beneficiary. Apple and Apple’s subsidiaries are third party beneficiaries of this Agreement. Upon your acceptance of the terms and conditions of this Agreement, Apple will have the right (and will be deemed to have accepted the right) to enforce the Agreement against the end-user as a third party beneficiary thereof. </p>
                    <p> Performance. FLATLAY will use commercially reasonable efforts to deliver the Services, provided that you accept all information “as is.” You acknowledge and agree that FLATLAY relies on the accuracy of outside sources, which may or may not be completely thorough and accurate and you will not rely on FLATLAY for the accuracy or completeness of the Services. FLATLAY reserves the right to add or subtract from the material presented in the Services. This may include discontinuing part of the Service. In the event that FLATLAY removes a material portion of the Service that you regularly and reasonably use in the course of your business, upon your timely request following the removal or announced removal, FLATLAY may provide a prorated credit to your account, as also noted above. ICE does not provide professional investment advice. </p>
                    <p> Some features of the Flatlay Mobile App may require you to have a social media account (e.g., Facebook Messenger, Twitter), including the chat function. Your social media accounts are subjects to the terms and conditions of the individual media providers. </p>
                    <p> California Consumer Rights Notice. The Site and the app may be used by both consumers and professionals. Pursuant to California Civil Code Sec. 1789.3, FLATLAY is required to provide the following information. The Site and Flatlay are provided by FLATLAY, Inc. located at 6201 Hollywood Boulevard, Suite 3207, Los Angeles, CA 90028 and reachable by email at support (at) flatlay.io. Access to the Site is free to everyone; access to Flatlay is by license and download only and subject to these terms. </p>
                    <p> If you would like to receive further information regarding the use of our service, or if you have any questions or complaints please feel free to contact FLATLAY directly to have the issue resolved. Please note that FLATLAY cannot provide a specific timeframe for any resolution. Should you remain unsatisfied with the service, you can also contact the Complaint Assistance Unit of the Division of Consumer Service of the Department of Consumer Affairs; they are reachable in writing at 1625 North Market Blvd., Suite N 112, Sacramento, CA 95834 or by telephone at (800) 952-5210. </p>

                    <p><span>LIMITATION OF LIABILITY.</span></p>
                    <p> FLATLAY’S LIABILITY TO YOU IS LIMITED. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL COMPANY BE LIABLE FOR DAMAGES OF ANY KIND (INCLUDING, BUT NOT LIMITED TO, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, LOST PROFITS, OR LOST DATA, REGARDLESS OF THE FORESEEABILITY OF THOSE DAMAGES) ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SITE OR ANY OTHER MATERIALS OR SERVICES PROVIDED TO YOU BY THE COMPANY. This limitation shall apply regardless of whether the damages arise out of breach of contract, tort, or any other legal theory or form of action. </p>
                    <p> You acknowledge that any reliance upon any of the opinions, facts, or recommendations provide in the Service is at your own risk. </p>
                    <p><span>LIMITED WARRANTY.</span></p>
                    <p> FLATLAY HEREBY DISCLAIMS ALL WARRANTIES. COMPANY IS MAKING THE SITE AVAILABLE “AS IS” WITHOUT WARRANTY OF ANY KIND. YOU ASSUME THE RISK OF ANY AND ALL DAMAGE OR LOSS FROM USE OF, OR INABILITY TO USE, THE SITE OR THE SERVICE. TO THE MAXIMUM EXTENT PERMITTED BY LAW, COMPANY EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE SITE, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF ACCURACY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT. COMPANY DOES NOT WARRANT THAT THE SITE OR THE SERVICE WILL MEET YOUR REQUIREMENTS OR THAT THE OPERATION OF THE SITE OR THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE. YOU ASSUME FULL RESPONSIBILITY FOR YOUR USE OF THE SITE AND SERVICES AND ANY THIRD-PARTY LINKS, AND YOUR REMEDY LINKED TO THE SITE AND/OR SERVICES IS LIMITED TO STOP USING THE SITE. </p>
                    <p><span>Governing Law.</span> This Agreement shall be construed in accordance with and governed by the laws of the United States and the State of California, without reference to their rules regarding conflicts of law. You hereby irrevocably consent to the exclusive jurisdiction of the state or federal courts in Los Angeles County, California in all disputes arising out of or related to the use of the Services.
                        <br />Third-Party Sites and Flatlay Merchants. FLATLAY has no control over, and no liability for any third party website or materials. FLATLAY works with a number of partners and affiliates whose Internet site(s) may be linked with the Site or within the app. Because FLATLAY has no control over the content and performance of these partner and affiliate site, FLATLAY makes no guarantees about the accuracy, currency, content, or quality of the information provided by such Site, and FLATLAY assumes no responsibility for unintended, objectionable, inaccurate, misleading, or unlawful content that may reside on those sites. Similarly, from time to time in connection with your use of the Site, you may have access to content items (including, but not limited to, the website) that are owned by third parties. You acknowledge and agree that FLATLAY makes no guarantees about, and assumes no responsibility for, the accuracy, currency, content, or quality of this third party content, and that, unless expressly provided otherwise, this Agreement shall govern your use of any and all third party content. Further, unless expressed otherwise, third party content does not indicate sponsorship of the Site or the Flatlay Mobile App by these third parties. </p>
                    <p> The Flatlay Mobile App contains information that is provided directly by the manufacturer or the retail seller, including, for example, product prices, sales, descriptions and sizes. FLATLAY makes no representations as to the accuracy of this information. FLATLAY depends on merchants to keep inventory details and availability up-to-date. The Flatlay Mobile App will confirm availability of a particular item once you go to your virtual shopping cart and again prior to completing your purchase. If a merchant is not able to ship a particular product you will be notified by email. </p>
                    <p><span>Promotion Codes. </span> FLATLAY may, from time to time, make available certain promotion codes. You cannot apply a promotion code to a previously registered subscription, and promotion codes may only be made available to new subscribers. </p>
                    <p><span>Modifications. </span> FLATLAY may, in its sole discretion and without prior notice, (a) revise this Agreement; (b) modify the Site and/or the Service; and/or (c) discontinue the Site and/or Flatlay at any time. FLATLAY shall post any revision to this Agreement to the Site, and the revision shall be effective immediately on such posting. You agree to review this Agreement and other online policies posted on the Site periodically to be aware of any revisions. You agree that, by continuing to use or access the Site following notice of any revision, you shall abide by any such revision. </p>
                    <p><span>Digital Millennium Copyright Act Compliance.</span></p>
                    <p> The Digital Millennium Copyright Act (“DMCA”) is applicable to Internet service providers. (17 U.S.C. § 512). Our Service do not allow for a subscriber, member or account holder to upload their own information. As such, FLATLAY does not foresee the applicability of the DMCA to the Service. FLATLAY will, however, terminate subscribers, members or account holders, where circumstances dictate and where FLATLAY deems appropriate, if these parties repeatedly infringe on another’s intellectual property rights. If you want to register a complaint regarding copyright infringement, you need to provide the following information after you have confirmed that you are, in fact, the copyright owner or rights holder:
                        <br />(i) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
                    </p>
                    <p> (ii) Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site. </p>
                    <p> (iii) Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the service provider to locate the material. </p>
                    <p> (iv) Information reasonably sufficient to permit the service provider to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted. </p>
                    <p> (v) A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law. </p>
                    <p> (vi) A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. </p>
                    <p><br /> FLATLAY, Inc. <br /> 6201 Hollywood Boulevard<br /> Suite 3207<br /> Los Angeles, CA 90028<br /> (972) 978-6076<br /> support (at) flatlay.io </p>
                    <p> Inappropriate Content. It is unlikely that any Flatlay or Site user will upload or make available information to others. However, should you upload, disseminate or otherwise make available information, you shall not make the following types of Content available. You agree not to upload, download, display, perform, transmit, or otherwise distribute any Content that (a) is libelous, defamatory, obscene, pornographic, abusive, or threatening; (b) advocates or encourages conduct that could constitute a criminal offense, give rise to civil liability, or otherwise violate any applicable local, state, national, or foreign law or regulation; or (c) advertises or otherwise solicits funds or is a solicitation for goods or services. FLATLAY reserves the right to terminate your receipt, transmission, or other distribution of any such material using the Service, and, if applicable, to delete any such material from its servers. FLATLAY intends to cooperate fully with any law enforcement officials or agencies in the investigation of any violation of this Agreement or of any applicable laws. </p>
                    <p> Prohibited Uses. FLATLAY imposes certain restrictions on your permissible use of the Site and the Service. You are prohibited from violating or attempting to violate any security features of the Site or Service, including, without limitation, (a) accessing content or data not intended for you, or logging onto a server or account that you are not authorized to access; (b) attempting to probe, scan, or test the vulnerability of the Service, the Site, or any associated system or network, or to breach security or authentication measures without proper authorization; (c) interfering or attempting to interfere with service to any user, host, or network, including, without limitation, by means of submitting a virus to the Site or Service, overloading, “flooding,” “spamming,” “mail bombing,” or “crashing;” (d) using the Site or Service to send unsolicited e-mail, including, without limitation, promotions, or advertisements for products or services; (e) forging any TCP/IP packet header or any part of the header information in any e-mail or in any posting using the Service; or (f) attempting to modify, reverse-engineer, decompile, disassemble, or otherwise reduce or attempt to reduce to a human-perceivable form any of the source code used by FLATLAY in providing the Site or Service. Any violation of system or network security may subject you to civil and/or criminal liability. </p>
                    <p> Flatlay makes it possible for you to use sites and services outside of Flatlay to distribute referral links to your network. Be mindful of your conduct both inside the Flatlay App and outside as it relates to Flatlay. For example, do not engage in unauthorized commercial communications or multi-level marketing schemes, solicit and/or collect App login information, collect users' content or information using traditional or automated means, or access an account belonging to someone else. If you have any questions about your conduct, please let us know. </p>
                    <p> Indemnity. You agree to indemnify FLATLAY for certain of your acts and omissions. You agree to indemnify, defend, and hold harmless FLATLAY, its affiliates, officers, directors, employees, consultants, agents, and representatives from any and all third party claims, losses, liability, damages, and/or costs (including reasonable attorney fees and costs) arising from your access to or use of the Site, your violation of this Agreement, or your infringement, or infringement by any other user of your account, of any intellectual property or other right of any person or entity. FLATLAY will notify you promptly of any such claim, loss, liability, or demand, and will provide you with reasonable assistance, at your expense, in defending any such claim, loss, liability, damage, or cost. </p>
                    <p> Termination of your Flatlay Card. As described above and in more detail in our Flatlay Card Terms, FLATLAY reserves the right to terminate your Flatlay Card and/or your access to the Flatlay Mobile App if, at Flatlay’s sole discretion, FLATLAY believes that you have violated this Agreement or any terms of the Flatlay Card Terms, you have more than one Flatlay Card, a mistake was made when opening or servicing your account, or that the use of your account is unauthorized, deceptive, fraudulent or otherwise unlawful and to do so without providing notice to you and any credits in your account will expire immediately and will not be reinstated. If your Flatlay Card is inactive for two (2) years consecutively, then FLATLAY reserves the right to deactivate and delete your card, including your account history and any account credits without notice. </p>
                    <p> You can delete your Flatlay Card by logging in online at www.flat-lay.com or by contacting us at support (at) flatlay.io. Please allow up to ten (10) business days for your account to be deleted and remember that your account credits are deleted along with your account. We will maintain account records only as required or allowed by law. </p>
                    <p> Severability and Waiver. If, for whatever reason, a court of competent jurisdiction finds any term or condition in this Agreement to be unenforceable, all other terms and conditions will remain unaffected and in full force and effect. No waiver of any breach of any provision of this Agreement shall constitute a waiver of any prior, concurrent, or subsequent breach of the same or any other provisions hereof, and no waiver shall be effective unless made in writing and signed by an authorized representative of the waiving party. </p>
                    <p> ACKNOWLEDGEMENT. BY USING THE SERVICE OR ACCESSING THE SITE, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF USE AND AGREE TO BE BOUND BY THEM. </p>
                    <Link to="/privacy">
                    <button className="terms-btn"><p>TERMS OF SERVICE</p></button>
                    </Link>

                </div>
            </div>
        </div>
    )
}

export default Terms