// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/enquiry": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact-us": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/physical-inventory": {
    params: {};
  };
  "/digital-goods": {
    params: {};
  };
  "/products-on-demand": {
    params: {};
  };
  "/tokenpay": {
    params: {};
  };
  "/payment-links": {
    params: {};
  };
  "/product-tiles": {
    params: {};
  };
  "/tokenizing-products": {
    params: {};
  };
  "/onchain-subscriptions": {
    params: {};
  };
  "/custom-tokens": {
    params: {};
  };
  "/metaverse-store": {
    params: {};
  };
  "/book-demo": {
    params: {};
  };
  "/d3": {
    params: {};
  };
  "/unstoppable-domains": {
    params: {};
  };
  "/polygon": {
    params: {};
  };
  "/crossmint": {
    params: {};
  };
  "/base": {
    params: {};
  };
  "/onchain-affiliate": {
    params: {};
  };
  "/roi": {
    params: {};
  };
  "/dpp": {
    params: {};
  };
  "/accept-invitation/:invitationId": {
    params: {
      "invitationId": string;
    };
  };
  "/plans": {
    params: {};
  };
  "/rewards": {
    params: {};
  };
  "/explore": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/blogs/categories/:category": {
    params: {
      "category": string;
    };
  };
  "/blogs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/affiliate/products": {
    params: {};
  };
  "/affiliate/products/:slug": {
    params: {
      "slug": string;
    };
  };
  "/analytics": {
    params: {};
  };
  "/analytics/dashboard": {
    params: {};
  };
  "/analytics/registration": {
    params: {};
  };
  "/analytics/style-center/product-tiles": {
    params: {};
  };
  "/analytics/style-center/product-links": {
    params: {};
  };
  "/analytics/account-settings": {
    params: {};
  };
  "/analytics/credits-and-activity": {
    params: {};
  };
  "/analytics/onchain-records": {
    params: {};
  };
  "/analytics/products": {
    params: {};
  };
  "/analytics/collections": {
    params: {};
  };
  "/analytics/purchase-history": {
    params: {};
  };
  "/analytics/shipping-management": {
    params: {};
  };
  "/analytics/plans": {
    params: {};
  };
  "/analytics/gamification": {
    params: {};
  };
  "/analytics/crossmint": {
    params: {};
  };
  "/analytics/affiliate/products": {
    params: {};
  };
  "/analytics/affiliate/products/:slug": {
    params: {
      "slug": string;
    };
  };
  "/analytics/affiliate/stores": {
    params: {};
  };
  "/analytics/affiliate/stores/:shopId": {
    params: {
      "shopId": string;
    };
  };
  "/analytics/affiliate/stores/:shopId/:slug": {
    params: {
      "shopId": string;
      "slug": string;
    };
  };
  "/analytics/blogs": {
    params: {};
  };
  "/analytics/blogs/new": {
    params: {};
  };
  "/analytics/blogs/:id": {
    params: {
      "id": string;
    };
  };
  "/analytics/changelog": {
    params: {};
  };
  "/analytics/changelog/:id": {
    params: {
      "id": string;
    };
  };
  "/shop-management": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/invoice/:txId": {
    params: {
      "txId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/enquiry" | "/terms" | "/about" | "/contact-us" | "/privacy" | "/physical-inventory" | "/digital-goods" | "/products-on-demand" | "/tokenpay" | "/payment-links" | "/product-tiles" | "/tokenizing-products" | "/onchain-subscriptions" | "/custom-tokens" | "/metaverse-store" | "/book-demo" | "/d3" | "/unstoppable-domains" | "/polygon" | "/crossmint" | "/base" | "/onchain-affiliate" | "/roi" | "/dpp" | "/accept-invitation/:invitationId" | "/plans" | "/rewards" | "/explore" | "/blogs" | "/blogs/categories/:category" | "/blogs/:slug" | "/affiliate/products" | "/affiliate/products/:slug" | "/analytics" | "/analytics/dashboard" | "/analytics/registration" | "/analytics/style-center/product-tiles" | "/analytics/style-center/product-links" | "/analytics/account-settings" | "/analytics/credits-and-activity" | "/analytics/onchain-records" | "/analytics/products" | "/analytics/collections" | "/analytics/purchase-history" | "/analytics/shipping-management" | "/analytics/plans" | "/analytics/gamification" | "/analytics/crossmint" | "/analytics/affiliate/products" | "/analytics/affiliate/products/:slug" | "/analytics/affiliate/stores" | "/analytics/affiliate/stores/:shopId" | "/analytics/affiliate/stores/:shopId/:slug" | "/analytics/blogs" | "/analytics/blogs/new" | "/analytics/blogs/:id" | "/analytics/changelog" | "/analytics/changelog/:id" | "/shop-management" | "/onboarding" | "/invoice/:txId" | "/*";
  };
  "./layouts/PublicLayout/PublicLayout.tsx": {
    id: "layouts/PublicLayout/PublicLayout";
    page: "/" | "/enquiry" | "/terms" | "/about" | "/contact-us" | "/privacy" | "/physical-inventory" | "/digital-goods" | "/products-on-demand" | "/tokenpay" | "/payment-links" | "/product-tiles" | "/tokenizing-products" | "/onchain-subscriptions" | "/custom-tokens" | "/metaverse-store" | "/book-demo" | "/d3" | "/unstoppable-domains" | "/polygon" | "/crossmint" | "/base" | "/onchain-affiliate" | "/roi" | "/dpp" | "/accept-invitation/:invitationId" | "/plans" | "/rewards" | "/explore" | "/blogs" | "/blogs/categories/:category" | "/blogs/:slug" | "/affiliate/products" | "/affiliate/products/:slug";
  };
  "./pages/public-pages/landings/home/HomePage.tsx": {
    id: "pages/public-pages/landings/home/HomePage";
    page: "/";
  };
  "./pages/public-pages/enquiry-page/EnquiryPage.jsx": {
    id: "pages/public-pages/enquiry-page/EnquiryPage";
    page: "/enquiry";
  };
  "./pages/public-pages/terms-page/TermsPage.jsx": {
    id: "pages/public-pages/terms-page/TermsPage";
    page: "/terms";
  };
  "./pages/public-pages/about/AboutUs.tsx": {
    id: "pages/public-pages/about/AboutUs";
    page: "/about";
  };
  "./pages/public-pages/contact-us/ContactUs.tsx": {
    id: "pages/public-pages/contact-us/ContactUs";
    page: "/contact-us";
  };
  "./pages/public-pages/privacy-page/PrivacyPage.jsx": {
    id: "pages/public-pages/privacy-page/PrivacyPage";
    page: "/privacy";
  };
  "./pages/public-pages/landings/physical-inventory/PhysicalInventoryPage.tsx": {
    id: "pages/public-pages/landings/physical-inventory/PhysicalInventoryPage";
    page: "/physical-inventory";
  };
  "./pages/public-pages/landings/digital-goods/DigitalGoodsPage.tsx": {
    id: "pages/public-pages/landings/digital-goods/DigitalGoodsPage";
    page: "/digital-goods";
  };
  "./pages/public-pages/landings/products-on-demand/ProductsOnDemandPage.tsx": {
    id: "pages/public-pages/landings/products-on-demand/ProductsOnDemandPage";
    page: "/products-on-demand";
  };
  "./pages/public-pages/landings/tokenpay/TokenpayPage.tsx": {
    id: "pages/public-pages/landings/tokenpay/TokenpayPage";
    page: "/tokenpay";
  };
  "./pages/public-pages/landings/payment-links/PaymentLinksPage.tsx": {
    id: "pages/public-pages/landings/payment-links/PaymentLinksPage";
    page: "/payment-links";
  };
  "./pages/public-pages/landings/product-tiles/ProductTilesPage.tsx": {
    id: "pages/public-pages/landings/product-tiles/ProductTilesPage";
    page: "/product-tiles";
  };
  "./pages/public-pages/landings/tokenizing-products/TokenizingProductsPage.tsx": {
    id: "pages/public-pages/landings/tokenizing-products/TokenizingProductsPage";
    page: "/tokenizing-products";
  };
  "./pages/public-pages/landings/onchain-subscriptions/OnchainSubscriptionsPage.tsx": {
    id: "pages/public-pages/landings/onchain-subscriptions/OnchainSubscriptionsPage";
    page: "/onchain-subscriptions";
  };
  "./pages/public-pages/landings/custom-tokens/CustomTokensPage.tsx": {
    id: "pages/public-pages/landings/custom-tokens/CustomTokensPage";
    page: "/custom-tokens";
  };
  "./pages/public-pages/landings/metaverse-showroom/MetaverseShowroomPage.tsx": {
    id: "pages/public-pages/landings/metaverse-showroom/MetaverseShowroomPage";
    page: "/metaverse-store";
  };
  "./pages/public-pages/landings/book-demo/BookDemoPage.tsx": {
    id: "pages/public-pages/landings/book-demo/BookDemoPage";
    page: "/book-demo";
  };
  "./pages/public-pages/landings/partner-pages/PartnerPageD3.tsx": {
    id: "pages/public-pages/landings/partner-pages/PartnerPageD3";
    page: "/d3";
  };
  "./pages/public-pages/landings/partner-pages/PartnerPageUnstoppableDomains.tsx": {
    id: "pages/public-pages/landings/partner-pages/PartnerPageUnstoppableDomains";
    page: "/unstoppable-domains";
  };
  "./pages/public-pages/landings/partner-pages/PartnerPagePolygon.tsx": {
    id: "pages/public-pages/landings/partner-pages/PartnerPagePolygon";
    page: "/polygon";
  };
  "./pages/public-pages/landings/partner-pages/PartnerPageCrossmint.tsx": {
    id: "pages/public-pages/landings/partner-pages/PartnerPageCrossmint";
    page: "/crossmint";
  };
  "./pages/public-pages/landings/partner-pages/PartnerPageBase.tsx": {
    id: "pages/public-pages/landings/partner-pages/PartnerPageBase";
    page: "/base";
  };
  "./pages/public-pages/landings/onchain-affiliate/OnchainAffiliatePage.tsx": {
    id: "pages/public-pages/landings/onchain-affiliate/OnchainAffiliatePage";
    page: "/onchain-affiliate";
  };
  "./pages/public-pages/landings/DIMST/DIMST.tsx": {
    id: "pages/public-pages/landings/DIMST/DIMST";
    page: "/roi";
  };
  "./pages/public-pages/landings/dpp/DPPPage.tsx": {
    id: "pages/public-pages/landings/dpp/DPPPage";
    page: "/dpp";
  };
  "./pages/public-pages/accept-invitation/AcceptInvitation.tsx": {
    id: "pages/public-pages/accept-invitation/AcceptInvitation";
    page: "/accept-invitation/:invitationId";
  };
  "./pages/public-pages/pricing/PricingPage.tsx": {
    id: "pages/public-pages/pricing/PricingPage";
    page: "/plans";
  };
  "./pages/public-pages/landings/social-quests/SocialQuests.tsx": {
    id: "pages/public-pages/landings/social-quests/SocialQuests";
    page: "/rewards";
  };
  "./pages/explore/ExplorePage.tsx": {
    id: "pages/explore/ExplorePage";
    page: "/explore";
  };
  "./pages/public-pages/public-blogs/PublicBlogs.tsx": {
    id: "pages/public-pages/public-blogs/PublicBlogs";
    page: "/blogs";
  };
  "./pages/public-pages/public-blogs/pages/CategoryPage/CategoryPage.tsx": {
    id: "pages/public-pages/public-blogs/pages/CategoryPage/CategoryPage";
    page: "/blogs/categories/:category";
  };
  "./pages/public-pages/public-blogs/pages/BlogDetailsPage/BlogDetailsPage.tsx": {
    id: "pages/public-pages/public-blogs/pages/BlogDetailsPage/BlogDetailsPage";
    page: "/blogs/:slug";
  };
  "./pages/affiliate/products/AffiliateProductsPagePublic.tsx": {
    id: "pages/affiliate/products/AffiliateProductsPagePublic";
    page: "/affiliate/products";
  };
  "./pages/affiliate/product/ProductPagePublic.tsx": {
    id: "affiliate-public";
    page: "/affiliate/products/:slug";
  };
  "./layouts/AuthGuardProducerLayout.tsx": {
    id: "layouts/AuthGuardProducerLayout";
    page: "/analytics" | "/analytics/dashboard" | "/analytics/registration" | "/analytics/style-center/product-tiles" | "/analytics/style-center/product-links" | "/analytics/account-settings" | "/analytics/credits-and-activity" | "/analytics/onchain-records" | "/analytics/products" | "/analytics/collections" | "/analytics/purchase-history" | "/analytics/shipping-management" | "/analytics/plans" | "/analytics/gamification" | "/analytics/crossmint" | "/analytics/affiliate/products" | "/analytics/affiliate/products/:slug" | "/analytics/affiliate/stores" | "/analytics/affiliate/stores/:shopId" | "/analytics/affiliate/stores/:shopId/:slug" | "/analytics/blogs" | "/analytics/blogs/new" | "/analytics/blogs/:id" | "/analytics/changelog" | "/analytics/changelog/:id";
  };
  "./pages/analytics/Analytics.tsx": {
    id: "pages/analytics/Analytics";
    page: "/analytics";
  };
  "./pages/dashboard/Dashboard.tsx": {
    id: "pages/dashboard/Dashboard";
    page: "/analytics/dashboard";
  };
  "./pages/simple-registration/SimpleRegistration.tsx": {
    id: "pages/simple-registration/SimpleRegistration";
    page: "/analytics/registration";
  };
  "./pages/tile-design/TileDesign.tsx": {
    id: "pages/tile-design/TileDesign";
    page: "/analytics/style-center/product-tiles";
  };
  "./pages/payment-link/PaymentLink.tsx": {
    id: "pages/payment-link/PaymentLink";
    page: "/analytics/style-center/product-links";
  };
  "./pages/settings/SettingsPage.tsx": {
    id: "pages/settings/SettingsPage";
    page: "/analytics/account-settings";
  };
  "./pages/credits-and-activity/CreditsAndActivity.tsx": {
    id: "pages/credits-and-activity/CreditsAndActivity";
    page: "/analytics/credits-and-activity";
  };
  "./pages/onchain-records/OnchainRecords.tsx": {
    id: "pages/onchain-records/OnchainRecords";
    page: "/analytics/onchain-records";
  };
  "./pages/products/Products.tsx": {
    id: "pages/products/Products";
    page: "/analytics/products";
  };
  "./pages/collections/Collections.tsx": {
    id: "pages/collections/Collections";
    page: "/analytics/collections";
  };
  "./pages/purchase-history/PurchaseHistory.tsx": {
    id: "pages/purchase-history/PurchaseHistory";
    page: "/analytics/purchase-history";
  };
  "./pages/shipping-management/ShippingManagement.tsx": {
    id: "pages/shipping-management/ShippingManagement";
    page: "/analytics/shipping-management";
  };
  "./pages/subscription-plans/SubscriptionPlans.tsx": {
    id: "pages/subscription-plans/SubscriptionPlans";
    page: "/analytics/plans";
  };
  "./pages/gamification/Gamification.tsx": {
    id: "pages/gamification/Gamification";
    page: "/analytics/gamification";
  };
  "./pages/crossmint/Crossmint.tsx": {
    id: "pages/crossmint/Crossmint";
    page: "/analytics/crossmint";
  };
  "./pages/affiliate/products/AffiliateProductsPage.tsx": {
    id: "pages/affiliate/products/AffiliateProductsPage";
    page: "/analytics/affiliate/products";
  };
  "./pages/affiliate/product/ProductPage.tsx": {
    id: "affiliate-private";
    page: "/analytics/affiliate/products/:slug";
  } | {
    id: "affiliate-private-stores";
    page: "/analytics/affiliate/stores/:shopId/:slug";
  };
  "./pages/affiliate/stores/AffiliateStores.tsx": {
    id: "pages/affiliate/stores/AffiliateStores";
    page: "/analytics/affiliate/stores";
  };
  "./pages/affiliate/stores/profile/AffiliateStoresProfile.tsx": {
    id: "pages/affiliate/stores/profile/AffiliateStoresProfile";
    page: "/analytics/affiliate/stores/:shopId";
  };
  "./pages/blogs/Blogs.tsx": {
    id: "pages/blogs/Blogs";
    page: "/analytics/blogs";
  };
  "./pages/blogs/components/BlogCreatePage.tsx": {
    id: "pages/blogs/components/BlogCreatePage";
    page: "/analytics/blogs/new";
  };
  "./pages/blogs/components/BlogEditPage.tsx": {
    id: "pages/blogs/components/BlogEditPage";
    page: "/analytics/blogs/:id";
  };
  "./pages/changelog/Changelog.tsx": {
    id: "pages/changelog/Changelog";
    page: "/analytics/changelog";
  };
  "./pages/changelog/components/ChangelogDetail.tsx": {
    id: "pages/changelog/components/ChangelogDetail";
    page: "/analytics/changelog/:id";
  };
  "./layouts/AuthGuardProducerLayoutShop.tsx": {
    id: "layouts/AuthGuardProducerLayoutShop";
    page: "/shop-management";
  };
  "./pages/shop-management/ShopManagement.tsx": {
    id: "pages/shop-management/ShopManagement";
    page: "/shop-management";
  };
  "./pages/onboarding/Onboarding.tsx": {
    id: "pages/onboarding/Onboarding";
    page: "/onboarding";
  };
  "./pages/invoice-template/InvoiceTemplate.tsx": {
    id: "pages/invoice-template/InvoiceTemplate";
    page: "/invoice/:txId";
  };
  "./pages/404/NotFoundPage.tsx": {
    id: "pages/404/NotFoundPage";
    page: "/*";
  };
};