export const categories: string[] = [
    "Fashion",
    "Technology",
    "Beauty",
    "Home",
    "Health",
    "Food",
    "Art",
    "Automotive",
    "Toys",
    "Books",
    "Entertainment",
    "Pet Supplies",
    "Sports",
    "Kids",
    "Luxury",
]